name: "Repository settings automation"
description: "Automate github repo settings"
inputs:
  diff:
    description: "True if you want to diff stuff"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.diff }}
